demo_homepage:
    path:     /
    defaults: { _controller: ProjektWypozyczalniaSamochodow:Default:index }

car_homepage:
    path:     /car/{id}
    defaults: { _controller: ProjektWypozyczalniaSamochodow:Default:car }

allCars_homepage:
    path:     /allCars
    defaults: { _controller: ProjektWypozyczalniaSamochodow:Default:allCars }

cart_homepage:
    path:     /cart
    defaults: { _controller: ProjektWypozyczalniaSamochodow:Default:cart }

history_homepage:
    path:     /history
    defaults: { _controller: ProjektWypozyczalniaSamochodow:Default:history }

pay_homepage:
    path:     /pay
    defaults: { _controller: ProjektWypozyczalniaSamochodow:Default:pay }

configuration_homepage:
    path:     /configuration/{id}
    defaults: { _controller: ProjektWypozyczalniaSamochodow:Default:configuration }

add_homepage:
    path:     /add/{id}
    defaults: { _controller: ProjektWypozyczalniaSamochodow:Review:addReview }

genre_homepage:
    path:     /genre/{genre}
    defaults: { _controller: ProjektWypozyczalniaSamochodow:Default:genre }