demo_homepage:
    path:     /
    defaults: { _controller: ProjektWypozyczalniaSamochodow:Default:index }

car_homepage:
    path:     /car/{id}
    defaults: { _controller: ProjektWypozyczalniaSamochodow:Default:car }

